CREATE DATABASE piccolo;
FLUSH PRIVILEGES;
CREATE USER 'pushdb'@'localhost' IDENTIFIED BY 'snmpfrom5';
GRANT ALL ON `%`.* TO 'pushdb'@'localhost';
CREATE USER 'pushdb'@'%' IDENTIFIED BY 'snmpfrom5';
GRANT ALL ON `%`.* TO 'pushdb'@'%';
USE piccolo;
CREATE TABLE push_app(
    app_id VARCHAR(100) NOT NULL PRIMARY KEY,
    created_time DATETIME DEFAULT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    registered_total_users INT NOT NULL DEFAULT 0,
    push_cnt INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE push_user(
    uid VARCHAR(100) NOT NULL,
    app_id VARCHAR(100) NOT NULL,
    device_token VARCHAR(300) NOT NULL DEFAULT '',
    os_type VARCHAR(1) NOT NULL,
    created_time DATETIME DEFAULT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT app_id_fk FOREIGN KEY (app_id) REFERENCES push_app(app_id)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    PRIMARY KEY(uid, app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE push_key(
    app_id VARCHAR(100) NOT NULL PRIMARY KEY,
    gcm_key VARCHAR(100) NOT NULL DEFAULT '',
    ios_key VARCHAR(100) NOT NULL DEFAULT '',
    ios_cert VARCHAR(100) NOT NULL DEFAULT '',
    created_time DATETIME DEFAULT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT app_id_fk2 FOREIGN KEY (app_id) REFERENCES push_app(app_id)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

